// ตัวอย่างข้อมูล dummy data สำหรับ columns ที่กำหนดไว้
export const historyBuildingData: any[] = [
  {
    key: 1,
    stepWork: "Site Inspection",
    Address: "123/45 Building A Floor 2",
    ReportTime: "2024-06-01 09:30",
    ReceiveTime: "2024-06-01 10:00",
    EventType: "Fire",
    NameOwner: "John Smith",
    NameStaff: "Engineer A",
    EventStep: "Completed",
  },
  {
    key: 2,
    stepWork: "Event Notification",
    Address: "456/78 Building B Floor 5",
    ReportTime: "2024-06-02 14:15",
    ReceiveTime: "2024-06-02 14:45",
    EventType: "Water Leak",
    NameOwner: "Jane Wilson",
    NameStaff: "Technician B",
    EventStep: "In Progress",
  },
  {
    key: 3,
    stepWork: "Damage Assessment",
    Address: "789/12 Building C Floor 1",
    ReportTime: "2024-06-03 08:00",
    ReceiveTime: "2024-06-03 08:30",
    EventType: "Power Outage",
    NameOwner: "Michael Johnson",
    NameStaff: "Staff C",
    EventStep: "Pending",
  },
];
