import { WarrantyDataType } from "../../../stores/interfaces/Warranty";

export const warrantyData: WarrantyDataType[] = [
  {
    key: '1',
    total: 5,
    address: '123/45 ถ.สุขุมวิท กรุงเทพฯ',
    owner: 'คุณสมชาย ใจดี',
    contact: 'คุณสมหญิง รักดี',
    nationality: 'ไทย',
    type: 'เครื่องใช้ไฟฟ้า',
    tel: '02-123-4567',
    email: 'somchai@email.com',
  },
  {
    key: '2', 
    total: 3,
    address: '789/12 ถ.เพชรบุรี กรุงเทพฯ',
    owner: 'คุณวิชัย มั่งมี',
    contact: 'คุณวิภา มั่งมี',
    nationality: 'ไทย',
    type: 'เครื่องใช้ไฟฟ้า',
    tel: '02-890-1234',
    email: 'wichai@email.com',
  },
  {
    key: '3',
    total: 4,
    address: '456/78 ถ.รัชดา กรุงเทพฯ',
    owner: 'คุณมานะ ตั้งใจ',
    contact: 'คุณมานี ตั้งใจ',
    nationality: 'ไทย', 
    type: 'เครื่องใช้ไฟฟ้า',
    tel: '02-345-6789',
    email: 'mana@email.com',
  },
  {
    key: '4',
    total: 2,
    address: '321/54 ถ.พระราม 9 กรุงเทพฯ',
    owner: 'คุณสมศักดิ์ ดีงาม',
    contact: 'คุณสมศรี ดีงาม',
    nationality: 'ไทย',
    type: 'เครื่องใช้ไฟฟ้า', 
    tel: '02-987-6543',
    email: 'somsak@email.com',
  },
  {
    key: '5',
    total: 6,
    address: '159/75 ถ.ลาดพร้าว กรุงเทพฯ',
    owner: 'คุณประเสริฐ รุ่งเรือง',
    contact: 'คุณประไพ รุ่งเรือง',
    nationality: 'ไทย',
    type: 'เครื่องใช้ไฟฟ้า',
    tel: '02-159-7532',
    email: 'prasert@email.com',
  }
];
